{{- if .Values.env -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}
  labels:
    {{- include "service-chart.labels" . | nindent 4 }}
{{- with .Values.env }}
data:
    {{- toYaml . | nindent 2 }}
{{- end }}
{{- end }}
