apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "service-chart.fullname" . }}
  labels:
    {{- include "service-chart.labels" . | nindent 4 }}
data:
  {{- include "service-chart.env" . | nindent 2 }}
