{{- if .Values.secrets -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "service-chart.fullname" . }}
{{- with .Values.secrets }}
data:
    {{- toYaml . | nindent 2 }}
{{- end }}
{{- end }}
